CREATE CONSTRAINT FOR (gt:GeoType) REQUIRE (gt.name) IS NODE KEY;
CREATE CONSTRAINT FOR (g:Geo) REQUIRE (g.id) IS NODE KEY;
CREATE CONSTRAINT FOR (t:TransportMode) REQUIRE (t.id) IS NODE KEY;
CREATE CONSTRAINT FOR (c:Commodity) REQUIRE (c.id) IS NODE KEY;
CREATE CONSTRAINT FOR (stat:CommodityStat) REQUIRE (stat.id) IS NODE KEY;
